import '@/app/globals.css'
import { Layout } from '@/components/Layout'
import type { Metadata } from 'next'

// metadataは後でまとめて
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" className="scroll-smooth">
      <body className="relative flex min-h-screen flex-col overflow-auto">
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
